
### GET ALL ITEMS
GET /api/items HTTP/1.1
Host: localhost:3000

### GET SINGLE ITEM
GET /api/items/3 HTTP/1.1
Host: localhost:3000

### CREATE ITEM
POST /api/items HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "name": "New Item"
}

### DELETE ITEM
DELETE /api/items/4 HTTP/1.1
Host: localhost:3000

### UPDATE ITEM
PUT /api/items/4 HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "name": "Updated Item"
}
